/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package oopseminar4;

import org.junit.jupiter.api.Test;

//import oopseminar4.data.Event;
//import oopseminar4.service.EventService;
//import java.util.Queue;

//import static org.junit.jupiter.api.Assertions.*;

class AppTest {
    @Test 
    void compareEventTest() {
            //Event event1 = new Event("ImpotantTask1!!!", 3);
            //Event event2 = new Event("ImpotantTask@!!!", 5);
            //System.out.println(event2.compareTo(event1));
            //EventService eventService = new EventService();
            //Queue<Event> tasks = eventService.getImportantTasks();
            //tasks.add(event2);
            //tasks.add(event1);
            //for (Event event : tasks) {
            //    System.out.println(event.getPriority());   
            //}
            //System.out.println(tasks);

            
    }
}
